mapping: Linear
lamda: 0.0
num_samples: 10
dataset: fmnist
base_dir: .
storage_path: .
model1:
  seed: 1
  name: pcktae
  latent_size: 8
  path: .
model2:
  seed: 2
  name: pcktae
  latent_size: 8
  path: .
output_name: PCKTAE
directory_to_explore: results/transformations/mapping_files/${output_name}
filters: ${output_name}.convex
