experiment_name: ResNet-NN
mapping: NeuralNetwork
hidden_size: 512  # same as the latent size
learning_rate: 0.001
epochs: 50
lamda: 0.01
num_samples: 100
base_dir: .
storage_path: ${base_dir}/results/transformations/${.experiment_name}
model1:
  seed: 1
  path: ${base_dir}/models/checkpoints/ResNet/MNIST/model_seed${.seed}.pth
  name: resnet
model2:
  seed: 2
  path: ${base_dir}/models/checkpoints/ResNet/MNIST/model_seed${.seed}.pth
  name: resnet
