mapping: NeuralNetwork
lamda: 0.0
num_samples: 10
hidden_size: 32
learning_rate: 0.008
epochs: 1
dataset: fmnist
base_dir: .
storage_path: .
model1:
  seed: 1
  name: pcktae
  latent_size: 8
  path: .
model2:
  seed: 2
  name: pcktae
  latent_size: 8
  path: .
