experiment_name: ResNet-NN
mapping: NeuralNetwork
hidden_size: 1000 # twice the size of the latent dimension
learning_rate: 0.01
epochs: 100
lamda: 0.1
num_samples: 100
base_dir: .
storage_path: ${base_dir}/results/transformations/${.experiment_name}
model1:
  seed: 1
  path: ${base_dir}/models/checkpoints/ResNet/MNIST/model_seed${.seed}.pth
  name: resnet
model2:
  seed: 2
  path: ${base_dir}/models/checkpoints/ResNet/MNIST/model_seed${.seed}.pth
  name: resnet
