mapping: Affine
sampling: equally
lamda: 0
num_samples: 200
hidden_size: 128
learning_rate: 0.004
epochs: 100
dataset: fmnist
base_dir: .
storage_path: .
model1:
  seed: 1
  name: vae
  latent_size: 8
  path: .
model2:
  seed: 2
  name: vae
  latent_size: 8
  path: .
visualization: pca