experiment_name: ResNetAE
dataset: cifar10
epochs: 50
batch_size: 64
base_dir: .
seeds: [1, 2, 3]
seed: 0
path: ${base_dir}/models/checkpoints/${experiment_name}/${name}_cifar10_seed${seed}_${epochs}.pth
name: resnet_ae
